// Metro wiring for a Clip Wallet phone app (CommonJS: metro.config.js requires it).
//
//   // metro.config.js
//   const { getDefaultConfig } = require("expo/metro-config");
//   const { withClipWallet } = require("@clip-wallet/mobile-kit/metro");
//   module.exports = withClipWallet(getDefaultConfig(__dirname), { configFile: "../../clip.config.ts", root: __dirname });
//
// What it adds:
//   - virtual:clip-wallet/config: the project's clip.config.ts, evaluated and validated in Node with the build
//     environment applied (WalletConnect id, mainnet checklist), plus the icon as a data: URI. Written to
//     node_modules/.cache/clip-wallet/config.js on every Metro start; the app never evaluates clip.config itself.
//   - shims for Node modules that dependencies require on code paths the wallet never runs (crypto, stream, pbkdf2);
//   - one React for the app and every package (hooks from a second copy crash);
//   - the "development" export condition and TypeScript's ".js → .ts" imports for workspace packages (monorepo only).
// Needs Node 22.18+ (it loads ESM helpers from @clip-wallet/config/node and clip.config.ts with type stripping).
const { mkdirSync, writeFileSync } = require("node:fs");
const path = require("node:path");

/** The resolved config and icon for the app bundle (exported for tests). */
function configModule(options) {
  const { buildEnv, iconDataUri, loadClipConfigSync, resolveBuildConfig } = require("@clip-wallet/config/node");
  const root = path.resolve(options.root || process.cwd());
  const configFile = path.resolve(root, options.configFile || "clip.config.ts");
  const configDir = path.dirname(configFile);
  const env = options.env || buildEnv([root, configDir]);
  const config = resolveBuildConfig(loadClipConfigSync(configFile), env, { checklistDir: configDir, fallbackWcEnv: "EXPO_PUBLIC_WC_PROJECT_ID" });
  const icon = iconDataUri(configDir, config.icon);
  return {
    config,
    icon,
    source:
      "// GENERATED by @clip-wallet/mobile-kit/metro from clip.config.ts on every Metro start. Do not edit.\n" +
      `Object.defineProperty(exports, "__esModule", { value: true });\nexports.default = ${JSON.stringify(config)};\nexports.icon = ${JSON.stringify(icon)};\n`,
  };
}

function withClipWallet(metroConfig, options = {}) {
  const root = path.resolve(options.root || metroConfig.projectRoot || process.cwd());
  const { source } = configModule({ ...options, root });
  const generated = path.join(root, "node_modules", ".cache", "clip-wallet", "config.js");
  mkdirSync(path.dirname(generated), { recursive: true });
  writeFileSync(generated, source);

  const shims = {
    "react-native-fast-pbkdf2": path.join(__dirname, "shims", "no-pbkdf2.js"),
    // Node's crypto for hdkey (Keystone SDK → bc-ur-registry-eth), backed by @noble/hashes.
    crypto: path.join(__dirname, "shims", "node-crypto.js"),
    // Node's stream for cipher-base (create-hash → bs58check → @keystonehq/bc-ur-registry): the browser build of
    // readable-stream, which is what bundlers for the web use for the same package.
    stream: require.resolve("readable-stream/readable-browser.js"),
  };

  const config = { ...metroConfig, resolver: { ...metroConfig.resolver } };
  // Workspace packages export their TypeScript source under the "development" condition (dist/ is for npm).
  config.resolver.unstable_conditionNames = ["development", ...(metroConfig.resolver?.unstable_conditionNames ?? ["require", "import"])];
  const upstream = metroConfig.resolver?.resolveRequest;
  config.resolver.resolveRequest = (context, moduleName, platform) => {
    const resolve = upstream ?? context.resolveRequest;
    if (moduleName === "virtual:clip-wallet/config") return { type: "sourceFile", filePath: generated };
    if (shims[moduleName]) return { type: "sourceFile", filePath: shims[moduleName] };
    // One React: packages with React hooks may have their own dev copy of react under pnpm; always use the app's.
    if (moduleName === "react" || moduleName.startsWith("react/")) {
      return resolve({ ...context, originModulePath: path.join(root, "package.json") }, moduleName, platform);
    }
    if (moduleName.startsWith(".") && moduleName.endsWith(".js")) {
      const from = path.dirname(context.originModulePath);
      if (from.includes(`${path.sep}packages${path.sep}`) && !from.includes(`${path.sep}node_modules${path.sep}`)) {
        for (const ext of [".ts", ".tsx"]) {
          try {
            return resolve(context, moduleName.slice(0, -3) + ext, platform);
          } catch {
            /* try next */
          }
        }
      }
    }
    return resolve(context, moduleName, platform);
  };
  return config;
}

module.exports = { withClipWallet, configModule };
