// Bundles src/preload/inpage-entry.ts (1Mask inpage providers) into src/preload/inpage.generated.ts as the body of
// `inpageMain(__CLIP_BOOT__)`, which the dapp preload runs in the page's main world. Output is gitignored.
// Same bundling as apps/mobile/scripts/build-inpage.mjs (see the Aptos note there).
import { build } from "esbuild";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const aptosEntryKeepsInit = {
  name: "aptos-ts-sdk-entry",
  setup(b) {
    b.onResolve({ filter: /^@aptos-labs\/ts-sdk$/ }, async (args) => {
      if (args.pluginData === "aptos-ts-sdk-entry") return undefined;
      const r = await b.resolve(args.path, { kind: args.kind, resolveDir: args.resolveDir, importer: args.importer, pluginData: "aptos-ts-sdk-entry" });
      return r.errors.length ? { errors: r.errors } : { path: r.path, sideEffects: true };
    });
  },
};

const out = await build({
  entryPoints: [join(root, "src/preload/inpage-entry.ts")],
  bundle: true,
  // Workspace packages: their "development" export condition is the TypeScript source.
  conditions: ["development"],
  write: false,
  format: "iife",
  platform: "browser",
  target: ["chrome130"],
  minify: true,
  legalComments: "none",
  logLevel: "warning",
  plugins: [aptosEntryKeepsInit],
});
const js = out.outputFiles[0].text;
const file = join(root, "src/preload/inpage.generated.ts");
mkdirSync(dirname(file), { recursive: true });
writeFileSync(
  file,
  `// GENERATED by scripts/build-inpage.mjs from src/preload/inpage-entry.ts. Do not edit.\n` +
    `/* eslint-disable */\n// @ts-nocheck\n` +
    `export function inpageMain(__CLIP_BOOT__) {\n${js}\n}\n`,
);
console.log(`inpage bundle: ${(js.length / 1024).toFixed(1)} KiB`);
