/**
 * Generates the reference pages that come straight from the source:
 *
 *   src/reference/config.md       the clip.config.ts schema (@clip-wallet/config's zod schema)
 *   src/reference/errors.md       error kinds and every ClipError code (@clip-wallet/core ERROR_CATEGORIES + a scan)
 *   src/reference/warnings.md     every Warning code and its messages (@clip-wallet/core WARNING_CODES, BG_MESSAGES)
 *   src/reference/dapp-errors.md  the codes 1Mask answers dapps with (@clip-wallet/1mask RpcErrorCode, CallsErrorCode)
 *
 * Bundled by esbuild and run from scripts/generate.mjs. Fails loudly when the schema grows a setting this file has no
 * description for, so the reference can't fall behind the code.
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import ts from "typescript";
import { z } from "zod";
import { clipConfigSchema, MAINNET_ACKNOWLEDGEMENT, NETWORK_FAMILIES, ROUTE_MODES, WALLETCONNECT_ENV } from "@clip-wallet/config";
import { BG_MESSAGES, BG_MESSAGE_PARTS, ERROR_CATEGORIES, WARNING_CODES, WARNING_DEFAULT_IDS, errorCategoryId, type BgMessageId } from "@clip-wallet/core";

const root = process.argv[2]!;
const out = process.argv[3]!;
const GENERATED = "<!-- Generated by apps/docs/scripts/reference.ts. Do not edit: change the source and rebuild. -->";

const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\{\{/g, "&#123;&#123;");
const code = (s: string) => "`" + s.replace(/`/g, "'") + "`";

/* ------------------------------------------------------------------ clip.config.ts */

/**
 * One plain sentence per setting. Keyed by dotted path ("route.filters.maxHops"). The generator fails when the
 * schema has a path that isn't here, or this table has a path the schema lost.
 */
const CONFIG_DOCS: Record<string, string> = {
  name: "The wallet's name. Shown in the stores, in wallet pickers (EIP-6963, Wallet Standard) and in every screen. Required.",
  icon: "The wallet's icon: a `.png` or `.svg` path next to the config, an https URL or a data URI. Ship it inside the extension: a mainnet build refuses a remote icon.",
  rdns: "Reverse-DNS id dapps see in EIP-6963 (`com.example.wallet`). Use a domain you own. Required.",
  description: "One sentence for the extension stores and wallet pickers (132 characters at most).",
  homepage: "The wallet's https website. WalletConnect metadata and the listing drafts link to it. Needed for mainnet.",
  extension: "The browser extension's identity.",
  "extension.key": "Base64 public key (SubjectPublicKeyInfo) that fixes the Chrome extension id. `create-clip-wallet` writes it; the private key never goes in the config. Needed for mainnet.",
  theme: "Colours, font and corner radius every screen reads.",
  "theme.accent": "Accent colour for buttons and highlights. Small accent text is derived from it to reach 4.5:1.",
  "theme.accentText": "Text colour on accent buttons. Must reach a 3:1 contrast with `accent`.",
  "theme.font": "Font family name used by the screens.",
  "theme.radius": "Corner radius in pixels (0 to 32).",
  networks: "Networks to turn on: `\"evm:*\"`, `\"evm:<chain id>\"`, an EVM network slug, or a family name. Each listed once. Test networks only while `mainnet` is `false`.",
  route: "Route-and-fund defaults on CLPRouter.",
  "route.mode": "How quotes are ranked when the user hasn't picked.",
  "route.filters": "Filters every route must pass.",
  "route.filters.iso20022": "Only routes through providers certified for ISO 20022 messaging.",
  "route.filters.mica": "Only routes through providers with a MiCA label.",
  "route.filters.energy": "Only routes with an energy label; pass `{ capKgPerTx }` to cap emissions per transaction (kgCO2e).",
  "route.filters.energy.capKgPerTx": "Maximum emissions per transaction in kgCO2e.",
  "route.filters.trustFloor": "The weakest verification tier a route may use. Allowed values are exported as `TRUST_TIERS` from `@clip-wallet/config`.",
  "route.filters.maxHops": "Maximum number of hops in a route (1 to 6).",
  "route.filters.deadlineS": "Deliver within this many seconds (compared with each quote's p90 time).",
  "route.filters.excludedJurisdictions": "Two-letter country codes whose routers a route must avoid.",
  "route.settleOnHedera": "Phase 3: also ask bonded Connectors for a quote when a payment needs money from another network. Off by default.",
  compatibilityMode: "Reserved for an opt-in per-site compatibility shim. Not implemented: keep it `false`.",
  hardware: "Hardware wallets offered in Settings: `\"ledger\"`, `\"keystone\"`, each listed once.",
  walletConnect: "WalletConnect settings.",
  "walletConnect.projectId": `Your WalletConnect Cloud project id. Leave it out of the file: set ${code(WALLETCONNECT_ENV)} in the build environment instead.`,
  passkeys: "Passkey unlock (WebAuthn PRF).",
  "passkeys.enabled": "Offer passkey unlock where the authenticator supports PRF. The password always keeps working.",
  "passkeys.rpOrigin": "Origin passkeys are bound to: an https origin you own, or the extension's own origin. Unset: the extension's origin.",
  services: "Optional hosted services. Unset = the feature is hidden.",
  "services.backupUrl": "Base URL of your `services/backup` deployment (passkey backup and settings sync).",
  "services.mediaProxyUrl": "Base URL of your `services/media-proxy` deployment. Unset: NFT media show placeholders and nothing remote is fetched.",
  "services.linkRelayUrl": "Base URL of your `services/link-relay` deployment (phone as signer, moving a wallet). Unset: those features are hidden.",
  "services.clipHandles": "Your ClipHandles contract on Hedera (`contracts/handles`). Unset: handles say they aren't switched on.",
  "services.clipHandles.address": "The contract's EVM address (`0x…`).",
  "services.clipHandles.contractId": "The contract's Hedera id (`0.0.x`).",
  "services.clipHandles.ledger": "Which Hedera ledger the contract is on.",
  languages: "The languages Settings → Language offers, from `LANGUAGES` (`en`, `de`, `fr`, `es`, `pt-BR`, `it`, `tr`, `ja`, `ko`, `zh-Hans`, `ar`, `hi`), each listed once. The first is the fallback. Unset: all twelve.",
  appId: "The desktop and phone app id, a reverse-domain id. Unset: `rdns`. The iOS bundle id and Android package are `appId` (hyphens become `_` on Android), the desktop app id `<appId>.desktop`; `platformIds(config)` lists them all.",
  scheme: "The deep-link URL scheme of the desktop and phone apps (`<scheme>://wc?uri=…`, `<scheme>://browse?url=…`). Unset: the wallet key, e.g. `acmewallet`.",
  desktop: "Desktop app overrides.",
  "desktop.appId": "The desktop app id (macOS bundle id, Windows AppUserModelID). Unset: `<appId>.desktop`.",
  mobile: "Phone app overrides.",
  "mobile.bundleId": "The iOS bundle id. Unset: `appId`.",
  "mobile.androidPackage": "The Android package. Unset: `appId`, with hyphens as `_`.",
  fees: "Reserved for Clip Cloud's hosted mode. Accepted (other fields are kept), never acted on by the kit. Default: off.",
  "fees.enabled": "Reserved; the kit never collects fees, whatever this says.",
  usage: "Reserved for Clip Cloud's hosted mode. Accepted (other fields are kept), never acted on by the kit. Default: off.",
  "usage.enabled": "Reserved; the kit never reports usage, whatever this says.",
  mainnet: `\`false\` (default) or the checklist object \`{ enabled: true, acknowledged: MAINNET_ACKNOWLEDGEMENT }\`. A mainnet build also needs \`mainnetProblems(config)\` to be empty.`,
};

/** Paths whose allowed values are documented by name instead of listed. */
const VALUES_BY_NAME: Record<string, string> = {
  "route.filters.trustFloor": "one of `TRUST_TIERS`",
};

type Json = {
  type?: string | string[];
  properties?: Record<string, Json>;
  required?: string[];
  default?: unknown;
  enum?: unknown[];
  const?: unknown;
  pattern?: string;
  minimum?: number;
  maximum?: number;
  minLength?: number;
  maxLength?: number;
  minItems?: number;
  items?: Json;
  anyOf?: Json[];
};

function typeOf(s: Json): string {
  if (s.anyOf) return s.anyOf.map(typeOf).filter((t) => t !== "unknown").join(" \\| ") || "unknown";
  if (s.enum) return s.enum.map((v) => JSON.stringify(v)).join(" \\| ");
  if (s.const !== undefined) return JSON.stringify(s.const);
  if (s.type === "array") return `${s.items ? typeOf(s.items) : "unknown"}[]`;
  if (Array.isArray(s.type)) return s.type.join(" \\| ");
  return s.type ?? "unknown";
}

function rulesOf(s: Json): string[] {
  const r: string[] = [];
  if (s.minLength !== undefined || s.maxLength !== undefined) r.push(`${s.minLength ?? 0} to ${s.maxLength ?? "∞"} characters`);
  if (s.minimum !== undefined || s.maximum !== undefined) r.push(`${s.minimum ?? "−∞"} to ${s.maximum ?? "∞"}`);
  if (s.minItems !== undefined) r.push(`at least ${s.minItems}`);
  return r;
}

function configPage(): string {
  const schema = z.toJSONSchema(clipConfigSchema, { io: "input", unrepresentable: "any" }) as Json;
  const rows: string[] = [];
  const seen = new Set<string>();
  const walk = (s: Json, path: string, required: boolean) => {
    if (path) {
      seen.add(path);
      const doc = CONFIG_DOCS[path];
      if (!doc) throw new Error(`reference.ts: clip.config.ts setting "${path}" has no description in CONFIG_DOCS`);
      const t = VALUES_BY_NAME[path] ?? (path === "mainnet" ? "false \\| { enabled: true, acknowledged: string }" : typeOf(s));
      const def = s.default !== undefined ? code(JSON.stringify(s.default)) : required ? "required" : "–";
      const rules = rulesOf(s).join("; ");
      const type = t.startsWith("one of") ? t : code(t);
      rows.push(`| ${code(path)} | ${type}<br>default: ${def} | ${esc(doc)}${rules ? ` (${rules})` : ""} |`);
    }
    const objectSchema = s.properties ? s : s.anyOf?.find((x) => x.properties);
    if (objectSchema?.properties) {
      for (const [k, v] of Object.entries(objectSchema.properties)) walk(v, path ? `${path}.${k}` : k, objectSchema.required?.includes(k) ?? false);
    }
  };
  walk(schema, "", false);
  for (const k of Object.keys(CONFIG_DOCS)) if (!seen.has(k)) throw new Error(`reference.ts: CONFIG_DOCS has "${k}", which the schema no longer has`);

  return `${GENERATED}
# clip.config.ts schema

Every setting \`defineConfig()\` from [\`@clip-wallet/config\`](./api/config.md) accepts, generated from its zod schema. Anything
not listed here is refused with "isn't a setting Clip Wallet knows". Only \`name\` and \`rdns\` are required; everything
else has a default.

For a guided tour with examples, see [Configure clip.config.ts](../kit/config.md).

| Setting | Type and default | What it does |
| --- | --- | --- |
${rows.join("\n")}

## Values

- **Network families** (\`NETWORK_FAMILIES\`): ${NETWORK_FAMILIES.map(code).join(", ")}.
- **Route modes** (\`ROUTE_MODES\`): ${ROUTE_MODES.map(code).join(", ")}.
- **WalletConnect project id**: read from ${code(WALLETCONNECT_ENV)} at build time when the file doesn't set it.

## Mainnet

::: danger Real funds
Clip Wallet is pre-release and has had no external audit. A mainnet build moves real money. Leave \`mainnet: false\`
unless you have completed the checklist the acknowledgement describes.
:::

\`mainnet\` accepts \`false\` or an object whose \`acknowledged\` field is exactly \`MAINNET_ACKNOWLEDGEMENT\`:

> ${esc(MAINNET_ACKNOWLEDGEMENT)}

Even then, the extension build refuses mainnet while \`mainnetProblems(config)\` lists anything: a placeholder rdns, no
homepage, no extension key, no WalletConnect project id, or a remote icon.

## Validation errors

\`defineConfig()\` throws a \`ConfigError\` whose \`problems\` are plain sentences, one per setting, prefixed with the
setting's path. \`validateConfig()\` returns them without throwing.
`;
}

/* ------------------------------------------------------------------ source scans */

function sourceFiles(dir: string): string[] {
  const outFiles: string[] = [];
  const walk = (d: string) => {
    for (const e of readdirSync(d)) {
      if (e === "node_modules" || e === "dist" || e === "test" || e === "vendor") continue;
      const p = join(d, e);
      const st = statSync(p);
      if (st.isDirectory()) walk(p);
      else if (/\.(ts|tsx)$/.test(e) && !/\.(test|d)\.tsx?$/.test(e)) outFiles.push(p);
    }
  };
  walk(dir);
  return outFiles;
}

function packageOf(file: string): string {
  const rel = relative(root, file).split("/");
  const pj = JSON.parse(readFileSync(join(root, rel[0]!, rel[1]!, "package.json"), "utf8")) as { name: string };
  return pj.name;
}

interface ErrorSite {
  code: string;
  pkg: string;
  message?: string;
}

/** Every `new ClipError(message, "code", …)` with a literal (or template) code in packages/*\/src. */
function scanClipErrors(): ErrorSite[] {
  const sites: ErrorSite[] = [];
  const files = readdirSync(join(root, "packages")).flatMap((p) => {
    const src = join(root, "packages", p, "src");
    try {
      return statSync(src).isDirectory() ? sourceFiles(src) : [];
    } catch {
      return [];
    }
  });
  for (const f of files) {
    const text = readFileSync(f, "utf8");
    if (!text.includes("ClipError(")) continue;
    const sf = ts.createSourceFile(f, text, ts.ScriptTarget.Latest, true, f.endsWith("x") ? ts.ScriptKind.TSX : ts.ScriptKind.TS);
    const visit = (n: ts.Node) => {
      if (ts.isNewExpression(n) && ts.isIdentifier(n.expression) && n.expression.text === "ClipError" && n.arguments && n.arguments.length >= 2) {
        const [m, c] = n.arguments as unknown as [ts.Expression, ts.Expression];
        let codeText: string | undefined;
        if (ts.isStringLiteral(c) || ts.isNoSubstitutionTemplateLiteral(c)) codeText = c.text;
        else if (ts.isTemplateExpression(c)) codeText = c.head.text + c.templateSpans.map((s) => `<${s.expression.getText(sf)}>${s.literal.text}`).join("");
        if (codeText) {
          const message = ts.isStringLiteral(m) || ts.isNoSubstitutionTemplateLiteral(m) ? m.text : undefined;
          sites.push({ code: codeText, pkg: packageOf(f), ...(message ? { message } : {}) });
        }
      }
      ts.forEachChild(n, visit);
    };
    visit(sf);
  }
  return sites;
}

function errorsPage(): string {
  const kinds = ERROR_CATEGORIES.map(
    (c) => `| ${c.codes.map(code).join(", ")} | ${esc(BG_MESSAGES[c.id] as string)} | ${code(c.id)} |`,
  );
  const sites = scanClipErrors();
  const byCode = new Map<string, { pkgs: Set<string>; message?: string }>();
  for (const s of sites) {
    const e = byCode.get(s.code) ?? { pkgs: new Set<string>() };
    e.pkgs.add(s.pkg);
    e.message ??= s.message;
    byCode.set(s.code, e);
  }
  const rows = [...byCode.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([c, e]) => {
      const kind = errorCategoryId(c);
      return `| ${code(c)} | ${[...e.pkgs].sort().map((p) => code(p.replace("@clip-wallet/", ""))).join(", ")} | ${kind ? esc(BG_MESSAGES[kind as BgMessageId] as string) : "–"} | ${e.message ? esc(e.message) : "–"} |`;
    });
  const sentences = Object.entries(BG_MESSAGE_PARTS.errors)
    .filter(([id]) => !id.startsWith("bg.err.cat."))
    .map(([id, text]) => `| ${code(id)} | ${esc(text)} |`);

  return `${GENERATED}
# Error codes

Every error Clip Wallet shows a person is a \`ClipError\` from [\`@clip-wallet/core\`](./api/core.md): a plain-words
\`userMessage\` with a next step, and a stable \`code\` for programs. Codes look like \`<area>/<kind>\` ("vault/locked",
"near/insufficient-funds"). Match on the code, show the message.

\`\`\`text
ClipError
  userMessage  "You don't have enough APT to pay the network fee."   ← show this
  code         "aptos/insufficient-funds"                           ← branch on this
  msg          { id, values, fallback }                             ← the translatable form, when there is one
\`\`\`

## Kinds of error

\`errorCategoryId(code)\` maps a code to a general message by its last part (or the whole code). The UI shows that
message in other languages when a module's exact sentence has no translation, with the English sentence underneath.

| Codes (whole code or last part) | General message | Message id |
| --- | --- | --- |
${kinds.join("\n")}

## Every ClipError code in the packages

Scanned from \`new ClipError(…, "code")\` in \`packages/*/src\` (${sites.length} call sites, ${byCode.size} codes).
\`<…>\` marks a part filled in at run time. "Kind" is the general message \`errorCategoryId()\` picks; "–" means the
module's own sentence is always shown.

| Code | Package | Kind | Example message |
| --- | --- | --- | --- |
${rows.join("\n")}

## Exact sentences

Sentences many modules use word for word. They are translated as they are (\`BG_MESSAGES\`).

| Message id | English |
| --- | --- |
${sentences.join("\n")}
`;
}

function warningsPage(): string {
  const raisedBy = new Map<string, Set<string>>();
  const files = readdirSync(join(root, "packages"))
    .filter((p) => p !== "core")
    .flatMap((p) => {
      const src = join(root, "packages", p, "src");
      try {
        return statSync(src).isDirectory() ? sourceFiles(src) : [];
      } catch {
        return [];
      }
    });
  for (const f of files) {
    const text = readFileSync(f, "utf8");
    for (const c of WARNING_CODES) {
      if (text.includes(`"${c}"`)) (raisedBy.get(c) ?? raisedBy.set(c, new Set()).get(c)!).add(packageOf(f).replace("@clip-wallet/", ""));
    }
  }
  const rows = WARNING_CODES.map((c) => {
    const id = WARNING_DEFAULT_IDS[c];
    return `| ${code(c)} | ${esc(BG_MESSAGES[id] as string)} | ${[...(raisedBy.get(c) ?? [])].sort().map(code).join(", ") || "–"} |`;
  });
  const specific = Object.entries(BG_MESSAGE_PARTS.warnings)
    .filter(([id]) => !Object.values(WARNING_DEFAULT_IDS).includes(id as BgMessageId))
    .map(([id, text]) => `| ${code(id)} | ${esc(text)} |`);

  return `${GENERATED}
# Warning codes

A \`DecodedRequest\` carries \`warnings\`: each has a \`level\` (\`info\`, \`caution\` or \`danger\`), a \`code\` from
\`WARNING_CODES\` in [\`@clip-wallet/core\`](./api/core.md), and a plain-words \`message\`. Chain modules raise most of them
while decoding; \`@clip-wallet/security\` adds the scam and look-alike ones; the background adds \`domain-mismatch\` for
sites it doesn't recognise. Approval screens show every warning, strongest first.

The level is the module's call for that request, so the same code can be a \`caution\` in one place and a
\`danger\` in another.

| Code | General message | Raised in |
| --- | --- | --- |
${rows.join("\n")}

"Raised in" lists the packages whose source mentions the code.

## Specific sentences

Modules use these word for word (or with values) when they know more than the general message says. In other
languages the translation is shown; where there is none, the general message for the code is shown with the English
sentence underneath.

| Message id | English |
| --- | --- |
${specific.join("\n")}
`;
}

/** `/** doc *\/ Name: 4001,` entries of an `as const` object, with their comments. */
function constCodes(file: string, name: string): { key: string; value: string; doc: string }[] {
  const text = readFileSync(file, "utf8");
  const sf = ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true);
  const found: { key: string; value: string; doc: string }[] = [];
  sf.forEachChild((n) => {
    if (!ts.isVariableStatement(n)) return;
    for (const d of n.declarationList.declarations) {
      if (!ts.isIdentifier(d.name) || d.name.text !== name || !d.initializer) continue;
      let init: ts.Expression = d.initializer;
      if (ts.isAsExpression(init)) init = init.expression;
      if (!ts.isObjectLiteralExpression(init)) continue;
      for (const p of init.properties) {
        if (!ts.isPropertyAssignment(p)) continue;
        const docs = ts.getLeadingCommentRanges(text, p.getFullStart()) ?? [];
        const doc = docs
          .map((r) => text.slice(r.pos, r.end))
          .join(" ")
          .replace(/\/\*\*?|\*\/|^\s*\*|\/\//gm, "")
          .replace(/\s+/g, " ")
          .trim();
        found.push({ key: p.name.getText(sf), value: p.initializer.getText(sf), doc });
      }
    }
  });
  if (!found.length) throw new Error(`reference.ts: ${name} not found in ${file}`);
  return found;
}

function dappErrorsPage(): string {
  const rpc = constCodes(join(root, "packages/1mask/src/shared/errors.ts"), "RpcErrorCode");
  const calls = constCodes(join(root, "packages/1mask/src/shared/calls.ts"), "CallsErrorCode");
  const row = (e: { key: string; value: string; doc: string }) => `| ${code(e.value)} | ${code(e.key)} | ${esc(e.doc || "–")} |`;
  return `${GENERATED}
# Dapp-facing error codes

What a dapp sees when Clip Wallet says no. 1Mask answers with standard codes, so wagmi, viem, ethers and the
ecosystem libraries already know them. Generated from \`RpcErrorCode\` and \`CallsErrorCode\` in
[\`@clip-wallet/1mask\`](./api/1mask.md).

## EIP-1193 and JSON-RPC

| Code | Name | Meaning |
| --- | --- | --- |
${rpc.map(row).join("\n")}

The most common ones in practice:

- **4001**: the person declined in the approval window. Show nothing scary; let them try again.
- **4100**: the site isn't connected yet, or asked for an account it wasn't given. Call \`eth_requestAccounts\` first.
- **4902**: the wallet doesn't have that chain. Clip only switches between the networks it ships with.
- **-32002**: a request from this site is already waiting in the wallet. Wait for it.

## EIP-5792 wallet calls and ERC-7682 auxiliary funds

| Code | Name | Meaning |
| --- | --- | --- |
${calls.map(row).join("\n")}

See [Wallet calls (EIP-5792)](../connect/wallet-calls.md) for when each is returned.
`;
}

writeFileSync(join(out, "config.md"), configPage());
writeFileSync(join(out, "errors.md"), errorsPage());
writeFileSync(join(out, "warnings.md"), warningsPage());
writeFileSync(join(out, "dapp-errors.md"), dappErrorsPage());
console.log("reference: config, errors, warnings, dapp-errors");
