// create-clip-wallet (EXPERIMENTAL): scaffold a branded Clip Wallet extension from templates/extension.
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, renameSync, writeFileSync, copyFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { createInterface } from "node:readline/promises";
import { fileURLToPath } from "node:url";
import { MAINNET_ACKNOWLEDGEMENT, validateConfig } from "@clip-wallet/config";

const PKG_DIR = join(dirname(fileURLToPath(import.meta.url)), "..");
export const TEMPLATE_DIR = join(PKG_DIR, "templates", "extension");
export const DEFAULT_ACCENT = "#4F46E5";
export const DEFAULT_NETWORKS = ["evm:*", "hedera", "solana", "bitcoin"];

/** "my-wallet" -> "My Wallet" @param {string} dir */
export function titleFromDir(dir) {
  const words = basename(dir).replace(/[^A-Za-z0-9]+/g, " ").trim().split(/\s+/).filter(Boolean);
  return words.length ? words.map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ") : "Clip Wallet";
}

/** npm-safe package name from a directory. @param {string} dir */
export function slugFromDir(dir) {
  return (
    basename(dir)
      .toLowerCase()
      .replace(/[^a-z0-9-]+/g, "-")
      .replace(/^-+|-+$/g, "") || "clip-wallet"
  );
}

/** Placeholder reverse domain; the next steps tell the user to change it to a domain they own. @param {string} slug */
export function rdnsFromSlug(slug) {
  return `com.example.${slug.replace(/[^a-z0-9]/g, "") || "wallet"}`;
}

/** "evm:*, hedera" -> ["evm:*", "hedera"] @param {string} text @returns {string[]} */
export function parseNetworks(text) {
  return text
    .split(/[\s,]+/)
    .map((s) => s.trim())
    .filter(Boolean);
}

/**
 * Validate answers with the real config schema. Returns plain-word problems (empty when fine).
 * @param {{ name: string, rdns: string, accent: string, networks: string[] }} a
 */
export function checkAnswers(a) {
  const r = validateConfig({ name: a.name, rdns: a.rdns, theme: { accent: a.accent }, networks: a.networks });
  return r.ok ? [] : r.problems;
}

/**
 * The clip.config.ts source for these answers.
 * @param {{ name: string, rdns: string, accent: string, networks: string[] }} a
 */
export function renderConfig(a) {
  const problems = checkAnswers(a);
  if (problems.length) throw new Error(`Can't write clip.config.ts:\n${problems.map((p) => `  - ${p}`).join("\n")}`);
  const s = JSON.stringify;
  return `import { defineConfig } from "@clip-wallet/config";

// Generated by create-clip-wallet. Every setting and its default is documented in @clip-wallet/config.
export default defineConfig({
  name: ${s(a.name)},
  // A reverse domain you own (EIP-6963 wallet discovery uses it).
  rdns: ${s(a.rdns)},
  icon: "./icon.svg",
  theme: { accent: ${s(a.accent)}, accentText: "#FFFFFF", font: "Inter", radius: 12 },
  networks: [${a.networks.map((n) => s(n)).join(", ")}],
  route: { mode: "balanced", filters: {} },
  compatibilityMode: false,
  hardware: ["ledger", "keystone"],
  // walletConnect.projectId is read from CLIP_WALLETCONNECT_PROJECT_ID (.env).
  passkeys: { enabled: true },
  // Test networks only. Mainnet needs { enabled: true, acknowledged: MAINNET_ACKNOWLEDGEMENT } after the checklist.
  mainnet: false,
});
`;
}

/** @param {string} dir */
function isEmptyDir(dir) {
  return !existsSync(dir) || readdirSync(dir).length === 0;
}

function findHarness() {
  for (const p of [join(PKG_DIR, "harness", "check.mjs"), join(PKG_DIR, "..", "..", "tools", "harness", "check.mjs")]) {
    if (existsSync(p)) return p;
  }
  return undefined;
}

/**
 * Copy the template into `targetDir` and write clip.config.ts. Returns the files written (relative).
 * @param {string} targetDir
 * @param {{ name: string, accent: string, networks: string[], rdns?: string }} answers
 */
export function scaffold(targetDir, answers) {
  const dir = resolve(targetDir);
  if (!isEmptyDir(dir)) throw new Error(`${targetDir} already exists and isn't empty. Pick a new folder name.`);
  const slug = slugFromDir(dir);
  const a = { ...answers, rdns: answers.rdns ?? rdnsFromSlug(slug) };
  const config = renderConfig(a); // validates before anything is written

  mkdirSync(dir, { recursive: true });
  cpSync(TEMPLATE_DIR, dir, { recursive: true });
  // npm drops dotfiles named .gitignore from packages, so the template ships them without the dot.
  renameSync(join(dir, "gitignore"), join(dir, ".gitignore"));
  renameSync(join(dir, "env.example"), join(dir, ".env.example"));

  const pkgPath = join(dir, "package.json");
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
  pkg.name = slug;
  writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
  writeFileSync(join(dir, "clip.config.ts"), config);

  const harness = findHarness();
  if (harness) {
    mkdirSync(join(dir, "tools", "harness"), { recursive: true });
    copyFileSync(harness, join(dir, "tools", "harness", "check.mjs"));
  }
  const svg = readFileSync(join(dir, "icon.svg"), "utf8").replace(DEFAULT_ACCENT, a.accent);
  writeFileSync(join(dir, "icon.svg"), svg);
  return { dir, slug, rdns: a.rdns, harness: Boolean(harness) };
}

/** @param {string} targetDir @param {{ slug: string, rdns: string, harness: boolean }} result */
export function nextSteps(targetDir, result) {
  return [
    "",
    `Created ${result.slug} in ${targetDir}.`,
    "",
    "Next steps:",
    `  cd ${targetDir}`,
    "  pnpm install",
    "  cp .env.example .env        # add your WalletConnect project id; never commit .env",
    `  edit clip.config.ts         # set rdns to a domain you own (now ${result.rdns})`,
    result.harness ? "  pnpm harness                # must pass before every commit" : "  pnpm harness                # (harness not bundled in this build; copy tools/harness/check.mjs from the Clip Wallet repo)",
    "",
    "Your wallet runs on test networks by default. Mainnet stays off until clip.config.ts has",
    "  mainnet: { enabled: true, acknowledged: MAINNET_ACKNOWLEDGEMENT }",
    "and you have completed the checklist it describes:",
    `  "${MAINNET_ACKNOWLEDGEMENT}"`,
    "",
    "create-clip-wallet is EXPERIMENTAL: the @clip-wallet packages are pre-release.",
  ].join("\n");
}

/** @param {string[]} argv */
export function parseArgs(argv) {
  /** @type {{ dir?: string, name?: string, accent?: string, networks?: string[], yes: boolean, help: boolean }} */
  const out = { yes: false, help: false };
  for (let i = 0; i < argv.length; i++) {
    const a = /** @type {string} */ (argv[i]);
    const val = () => {
      const v = argv[++i];
      if (v === undefined) throw new Error(`${a} needs a value`);
      return v;
    };
    if (a === "--help" || a === "-h") out.help = true;
    else if (a === "--yes" || a === "-y") out.yes = true;
    else if (a === "--name") out.name = val();
    else if (a === "--accent") out.accent = val();
    else if (a === "--networks") out.networks = parseNetworks(val());
    else if (a.startsWith("-")) throw new Error(`Unknown option ${a}. Run with --help.`);
    else if (!out.dir) out.dir = a;
    else throw new Error(`Only one folder name, please (got ${out.dir} and ${a}).`);
  }
  return out;
}

export const HELP = `create-clip-wallet (experimental)

Usage: npx create-clip-wallet <folder> [--name "My Wallet"] [--accent #4F46E5] [--networks "evm:*,hedera"] [--yes]

Networks: "evm:*", "evm:<chain id>", "hedera", "solana", "bitcoin". Test networks only by default.`;

/**
 * Ask until the answer passes `check` (which returns a problem or undefined).
 * @param {{ question(q: string): Promise<string> }} rl
 * @param {string} q
 * @param {string} def
 * @param {(v: string) => string | undefined} check
 */
async function ask(rl, q, def, check) {
  for (;;) {
    const v = (await rl.question(`${q} (${def}): `)).trim() || def;
    const problem = check(v);
    if (!problem) return v;
    process.stdout.write(`  ${problem}\n`);
  }
}

/**
 * Run the CLI. `io` is injectable for tests.
 * @param {string[]} argv
 * @param {{ question?: (q: string) => Promise<string>, log?: (s: string) => void }} [io]
 */
export async function main(argv, io = {}) {
  const log = io.log ?? ((s) => process.stdout.write(`${s}\n`));
  const args = parseArgs(argv);
  if (args.help) {
    log(HELP);
    return 0;
  }
  const rl = io.question ? { question: io.question, close() {} } : createInterface({ input: process.stdin, output: process.stdout });
  try {
    const dir = args.dir ?? (args.yes ? "my-wallet" : await ask(rl, "Folder", "my-wallet", (v) => (isEmptyDir(resolve(v)) ? undefined : "That folder isn't empty.")));
    const rdns = rdnsFromSlug(slugFromDir(resolve(dir)));
    /** @param {string} field @param {Partial<{ name: string, accent: string, networks: string[] }>} current */
    const pick = (field, current) => {
      const probe = { name: "Clip Wallet", rdns, accent: DEFAULT_ACCENT, networks: DEFAULT_NETWORKS, ...current };
      const hit = checkAnswers(probe).find((p) => p.startsWith(field));
      return hit?.replace(/^[^:]*: /, "");
    };
    const defName = titleFromDir(dir);
    const name = args.name ?? (args.yes ? defName : await ask(rl, "Wallet name", defName, (v) => pick("name", { name: v })));
    const accent = args.accent ?? (args.yes ? DEFAULT_ACCENT : await ask(rl, "Accent colour", DEFAULT_ACCENT, (v) => pick("theme", { accent: v })));
    const networks =
      args.networks ??
      (args.yes
        ? DEFAULT_NETWORKS
        : parseNetworks(await ask(rl, "Networks", DEFAULT_NETWORKS.join(", "), (v) => pick("networks", { networks: parseNetworks(v) }))));
    const result = scaffold(dir, { name, accent, networks, rdns });
    log(nextSteps(dir, result));
    return 0;
  } finally {
    rl.close();
  }
}
