// Listing-submission drafts for a kit-built wallet's own identity, written to docs/listings/. Nothing is submitted:
// each file says what the target registry wants, the exact entry for this wallet, and what to finish first. The
// formats follow each registry's docs as of the kit release (sources at the end of every file); check them again
// before you open a pull request.
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * @typedef {{ name: string, description: string, rdns: string, homepage?: string, extensionId: string, key: string,
 *   slug: string, networks: string[], version: string }} ListingIdentity
 */

const DRAFT = (/** @type {string} */ name) => `> DRAFT ONLY, generated by create-clip-wallet for ${name}. Nothing has been submitted. Regenerate with
> \`pnpm wallet:listings\` after you change wallet.identity.json, and check the registry's current rules first.`;

/** @param {ListingIdentity} id */
const site = (id) => id.homepage ?? `https://${id.rdns.split(".").slice(0, 2).reverse().join(".")}`;
/** @param {ListingIdentity} id */
const store = (id) => `https://chromewebstore.google.com/detail/${id.extensionId}`;
/** @param {ListingIdentity} id @param {string} family */
const has = (id, family) => id.networks.some((n) => n === family || n.startsWith(`${family}:`));

const PREREQS = (/** @type {ListingIdentity} */ id) => `## Before you submit anything
- [ ] The extension is published on the Chrome Web Store under id \`${id.extensionId}\` (fixed by \`extension.key\` in
      wallet.identity.json; keep .keys/extension.pem safe and out of git).
- [ ] \`${site(id)}\` is live and says who runs ${id.name}, how recovery works (the phrase never leaves the device) and
      how to get support. ${id.homepage ? "" : "Set `homepage` in wallet.identity.json: this placeholder is derived from the rdns."}
- [ ] You own the domain behind \`${id.rdns}\`.
- [ ] Icons are hosted at stable https URLs you control (PNG, square).
- [ ] Registries list production wallets: finish MAINNET.md first.`;

/** @param {ListingIdentity} id */
function eip6963(id) {
  return `# EIP-6963 identity: ${id.name}

${DRAFT(id.name)}

EIP-6963 has no central registry: a wallet announces itself on every page with \`eip6963:announceProvider\`, and dapps
(wagmi, RainbowKit, Web3Modal/AppKit, ConnectKit, Web3-Onboard) list whatever answers. What has to be right is what
${id.name} announces, and that nobody else announces the same rdns.

| Field | Value | Where it comes from |
| --- | --- | --- |
| \`info.name\` | ${id.name} | wallet.identity.json \`name\` |
| \`info.rdns\` | \`${id.rdns}\` | wallet.identity.json \`rdns\` (a reverse domain you own) |
| \`info.icon\` | data:image/svg+xml;base64,… | icon.svg (next to clip.config.ts), inlined at build time |
| \`info.uuid\` | a fresh UUIDv4 per page load | 1Mask |
| Chrome extension id | \`${id.extensionId}\` | wallet.identity.json \`extension.key\` |

${id.name} never announces \`org.coldai.clipwallet\` (Clip Wallet's own rdns) and never claims \`window.ethereum\` unless
nothing else owns it.

## How dapps target it
\`\`\`ts
// wagmi: EIP-6963 discovery is on by default; to show only ${id.name}:
import { injected } from "wagmi/connectors";
injected({ target: { id: "${id.rdns}", name: "${id.name}", provider: () => undefined } });
// or find it in the store: createStore() from "mipd", then store.findProvider({ rdns: "${id.rdns}" })
\`\`\`

## Places that key on the rdns
- WalletConnect Explorer listing: the \`rdns\` field (see walletconnect-explorer.md) lets AppKit merge the injected
  wallet with its listing instead of showing it twice.
- Wallet lists that ship static metadata (e.g. RainbowKit wallet packs) match on the rdns.

${PREREQS(id)}

## Sources
- https://eips.ethereum.org/EIPS/eip-6963
- https://github.com/wevm/mipd
- https://wagmi.sh/core/api/connectors/injected
`;
}

/** @param {ListingIdentity} id */
function walletConnect(id) {
  const chains = [];
  if (id.networks.some((n) => n.startsWith("evm:"))) chains.push("eip155:1", "eip155:8453", "eip155:295");
  if (has(id, "hedera")) chains.push("hedera:mainnet");
  if (has(id, "solana")) chains.push("solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp");
  if (has(id, "bitcoin")) chains.push("bip122:000000000019d6689c085ae165831e93");
  const entry = {
    name: id.name,
    description: id.description,
    homepage: site(id),
    image_url: `${site(id)}/walletconnect-icon-512.png`,
    rdns: id.rdns,
    injected: [{ namespace: "eip155", injected_id: id.rdns }],
    app: { browser: store(id) },
    chains,
    supported_standards: ["eip-6963", "walletconnect-v2"],
  };
  return `# WalletConnect Explorer (Reown) listing: ${id.name}

${DRAFT(id.name)}

Wallets are listed in the WalletConnect Explorer (the wallet list AppKit and WalletConnect-powered dapps show) through
the Reown dashboard: cloud.reown.com, your wallet project, "Get listed". Reown reviews the submission and tests the
wallet. ${id.name}'s WalletConnect side uses its own project id (CLIP_WALLETCONNECT_PROJECT_ID in .env,
never committed); the Explorer listing belongs to that same project.

## Draft entry
\`\`\`json
${JSON.stringify(entry, null, 2)}
\`\`\`

Notes:
- \`rdns\` and \`injected_id\` are the EIP-6963 rdns, so AppKit shows one ${id.name} entry for the extension and for
  WalletConnect, not two.
- \`chains\` must only list mainnets ${id.name} supports in its release build (CAIP-2). Test networks are not listed.
- The WalletConnect metadata the extension sends (name, url, icons) comes from wallet.identity.json; \`url\` is
  \`${site(id)}\`.
- Reown asks for a 512×512 PNG icon and a short demo of connecting and signing.

${PREREQS(id)}

## Sources
- https://docs.reown.com/cloud/explorer-submission
- https://docs.reown.com/walletkit/overview
`;
}

/** @param {ListingIdentity} id */
function tonConnect(id) {
  const entry = {
    app_name: id.key,
    name: id.name,
    image: `${site(id)}/tonconnect-icon-288.png`,
    about_url: site(id),
    bridge: [{ type: "js", key: id.key }],
    platforms: ["chrome"],
    features: [{ name: "SendTransaction", maxMessages: 255, extraCurrencySupported: false }, { name: "SignData", types: ["text", "binary", "cell"] }],
  };
  return `# TON Connect wallets-list entry: ${id.name}

${DRAFT(id.name)}

Submitting means a pull request that appends this entry to \`wallets-v2.json\` in github.com/ton-connect/wallets-list,
validated against \`wallets-v2.schema.json\`. ${id.name}'s build already answers as this entry: the JS bridge is
\`window.${id.key}.tonconnect\` and \`DeviceInfo.appName\` is \`${id.key}\` (the wallet key from the name, set by
@clip-wallet/extension-kit).

\`\`\`json
${JSON.stringify(entry, null, 2)}
\`\`\`

Notes:
- \`maxMessages: 255\` is wallet v5r1 (what the vault derives). \`SignMessage\` and \`EmbeddedRequest\` are not offered.
- The image must be a 288×288 PNG with a solid background and no rounded corners, at a stable https URL ending in .png.
- js bridge only: it's a browser extension, so \`universal_url\` and \`deepLink\` are left out.

${PREREQS(id)}

## Sources
- https://github.com/ton-connect/wallets-list
- https://github.com/ton-connect/docs/blob/main/spec/wallets-list.md
`;
}

/** @param {ListingIdentity} id */
function near(id) {
  return `# NEAR: NEAR Connect and NEAR Wallet Selector: ${id.name}

${DRAFT(id.name)}

- **NEAR Connect** (recommended by the NEAR Infra Committee): no pull request needed for the injected path. 1Mask answers
  NEAR Connect's \`near-selector-ready\` event with a \`near-wallet-injected\` wallet named ${id.name}.
- **NEAR Wallet Selector**: dapps add the module themselves, pointed at ${id.name}'s global:
  \`\`\`ts
  import { setupClipWallet } from "@clip-wallet/kit-modules/near";
  setupWalletSelector({ network: "testnet", modules: [setupClipWallet({ globalKey: "${id.key}" })] });
  \`\`\`
  or you upstream it as \`@near-wallet-selector/${id.slug}\`.

## PR to near/wallet-selector
**Title:** \`feat: add ${id.name} (injected) module\`

\`\`\`md
## Summary
Adds \`@near-wallet-selector/${id.slug}\`, an injected-wallet module for ${id.name}, a non-custodial browser extension.
- Module type: injected, id \`${id.slug}\`. Detection: \`window.${id.key}.near\`.
- Supports signIn / signOut / getAccounts, signAndSendTransaction(s), signMessage (NEP-413).
- Not supported: signTransaction / signDelegateAction (the wallet signs and sends in one approved step).

## Listing criteria
- Custody: non-custodial, disclosed during onboarding.
- Security statement: <link, dated>
- User guide: ${site(id)}
- Chrome Web Store: ${store(id)}
- Testnet: supported (the default build is testnet-only).
\`\`\`

${PREREQS(id)}

## Sources
- https://github.com/near/wallet-selector (CONTRIBUTING.md, listing criteria)
- https://github.com/azbang/near-connect
`;
}

/** @param {ListingIdentity} id */
function stellar(id) {
  return `# Stellar Wallets Kit module: ${id.name}

${DRAFT(id.name)}

Stellar Wallets Kit (github.com/Creit-Tech/Stellar-Wallets-Kit) lists wallets as modules implementing its
\`ModuleInterface\`; its guide asks for a pull request with the module. Until it is merged, dapps add it themselves:

\`\`\`ts
import { ClipWalletModule } from "@clip-wallet/kit-modules/stellar";
StellarWalletsKit.init({ modules: [...defaultModules(), new ClipWalletModule({ globalKey: "${id.key}" })] });
\`\`\`

## PR to Creit-Tech/Stellar-Wallets-Kit
**Title:** \`feat(modules): add ${id.name} module\`

\`\`\`md
## Summary
Adds \`${id.name.replace(/[^A-Za-z0-9]/g, "")}Module\` (id \`${id.slug}\`, ModuleType.HOT_WALLET) for ${id.name}, a non-custodial browser extension.
- Detection: \`window.${id.key}.stellar\`; isAvailable() answers synchronously.
- The injected provider implements SEP-43 (getAddress, signTransaction, signAuthEntry, signMessage (SEP-53), getNetwork).
- No extra dependencies or polyfills.
- Icon: ${site(id)}/stellar-icon.png · Chrome Web Store: ${store(id)}
\`\`\`

${PREREQS(id)}

## Sources
- https://github.com/Creit-Tech/Stellar-Wallets-Kit/blob/main/docs/files/wallets/create-wallet-module.md
- https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0043.md
`;
}

/** @param {ListingIdentity} id */
function beacon(id) {
  return `# Tezos Beacon wallet list: ${id.name}

${DRAFT(id.name)}

Beacon dapps find extensions by postMessage ping/pong (any extension that answers shows up). The curated list in the
Beacon UI is \`tezosExtensionList\` in github.com/airgap-it/beacon-sdk (\`scripts/blockchains/tezos.ts\`), keyed by the
browser extension id, which ${id.name}'s page relay answers with.

## PR to airgap-it/beacon-sdk
**Title:** \`feat(wallet-list): add ${id.name} browser extension\`

\`\`\`ts
{
  key: '${id.slug.replace(/-/g, "_")}_chrome',
  id: '${id.extensionId}',
  name: '${id.name.replace(/'/g, "\\'")}',
  shortName: '${String(id.name.split(/\s+/)[0]).replace(/'/g, "\\'")}',
  color: '',
  logo: 'extension-${id.slug}.png',
  link: '${site(id)}'
}
\`\`\`

Supports permission_request, operation_request and sign_payload_request; broadcast_request answers BROADCAST_ERROR.
Test with a Taquito \`BeaconWallet\` dapp on shadownet first (permission, transfer, FA2 transfer, delegation, sign payload).

${PREREQS(id)}

## Sources
- https://github.com/airgap-it/beacon-sdk/blob/master/scripts/blockchains/tezos.ts
- https://docs.walletbeacon.io
`;
}

/** @param {ListingIdentity} id */
function useWallet(id) {
  return `# Algorand use-wallet third-party adapter: ${id.name}

${DRAFT(id.name)}

use-wallet v5 lists third-party adapters in "Supported Wallets → Third-Party Adapters". Criteria: public source repo
linked from the npm package, an open-source licence, the adapter contract (extends \`BaseWallet\` from
\`@txnlab/use-wallet/adapter\`, a factory returning \`WalletAdapterConfig\`, a \`WALLET_ID\` export, peer deps
\`@txnlab/use-wallet ^5\` and \`algosdk ^3\`), active maintenance, npm provenance recommended.

\`@clip-wallet/kit-modules/algorand\` already follows the contract; for ${id.name}, publish a small adapter package that
re-exports it with your id and global:

\`\`\`ts
import { clipWallet } from "@clip-wallet/kit-modules/algorand";
export const WALLET_ID = "${id.slug}";
export const wallet = (options = {}) => clipWallet({ ...options, globalKey: "${id.key}", metadata: { name: "${id.name}", icon: "<data URI>" } });
\`\`\`

## Issue/PR to TxnLab/use-wallet
**Title:** \`docs: list ${id.name} third-party adapter\`

\`\`\`md
- npm: <package>  · Source: <repo url> (Apache-2.0)
- Wallet: ${id.name}, a non-custodial browser extension (window.${id.key}.algorand: ARC-1 signTxns, ARC-6 enable).
- Contract: extends BaseWallet; WALLET_ID = "${id.slug}"; peer deps @txnlab/use-wallet ^5, algosdk ^3.
\`\`\`

${PREREQS(id)}

## Sources
- https://github.com/TxnLab/use-wallet/blob/main/docs/resources/third-party-adapters.md
`;
}

/**
 * Write the drafts for the families this wallet turns on. Returns the files written (relative to root).
 * @param {string} root @param {ListingIdentity} id
 */
export function writeListings(root, id) {
  const dir = join(root, "docs", "listings");
  mkdirSync(dir, { recursive: true });
  /** @type {[string, string, boolean, string][]} file, title, applies, why not */
  const all = [
    ["eip-6963.md", "EIP-6963 identity (every EVM dapp)", id.networks.some((n) => n.startsWith("evm:")), "EVM is off"],
    ["walletconnect-explorer.md", "WalletConnect Explorer (Reown)", true, ""],
    ["ton-connect.md", "TON Connect wallets-list", has(id, "ton"), "TON is off"],
    ["near.md", "NEAR Connect / NEAR Wallet Selector", has(id, "near"), "NEAR is off"],
    ["stellar-wallets-kit.md", "Stellar Wallets Kit", has(id, "stellar"), "Stellar is off"],
    ["beacon.md", "Tezos Beacon wallet list", has(id, "tezos"), "Tezos is off"],
    ["use-wallet.md", "Algorand use-wallet", has(id, "algorand"), "Algorand is off"],
  ];
  const render = { "eip-6963.md": eip6963, "walletconnect-explorer.md": walletConnect, "ton-connect.md": tonConnect, "near.md": near, "stellar-wallets-kit.md": stellar, "beacon.md": beacon, "use-wallet.md": useWallet };
  const written = [];
  for (const [file, , applies] of all) {
    if (!applies) continue;
    writeFileSync(join(dir, file), render[/** @type {keyof typeof render} */ (file)](id));
    written.push(join("docs", "listings", file));
  }
  const rows = all.map(([file, title, applies, why]) => `| ${title} | ${applies ? `[${file}](${file})` : `not drafted: ${why} in clip.config.ts`} |`);
  writeFileSync(
    join(dir, "README.md"),
    `# Listing drafts for ${id.name}

${DRAFT(id.name)}

| | |
| --- | --- |
| Name | ${id.name} |
| rdns (EIP-6963) | \`${id.rdns}\` |
| Chrome extension id | \`${id.extensionId}\` |
| Wallet key (window global, TON Connect) | \`${id.key}\` |
| Website | ${site(id)} |
| Kit version | @clip-wallet/extension-kit ${id.version} |

| Registry | Draft |
| --- | --- |
${rows.join("\n")}

${PREREQS(id)}
`,
  );
  written.unshift(join("docs", "listings", "README.md"));
  return written;
}
