// Bundles src/browser/inpage-entry.ts (1Mask inpage + content bridge) into one IIFE string the WebView injects.
// Output: src/browser/inpage.generated.ts (gitignored). Runs before start/typecheck/test.
import { build } from "esbuild";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = await build({
  entryPoints: [join(root, "src/browser/inpage-entry.ts")],
  bundle: true,
  write: false,
  format: "iife",
  platform: "browser",
  target: ["safari15", "chrome100"],
  minify: true,
  legalComments: "none",
  logLevel: "warning",
});
const js = out.outputFiles[0].text;
const file = join(root, "src/browser/inpage.generated.ts");
mkdirSync(dirname(file), { recursive: true });
writeFileSync(
  file,
  `// GENERATED by scripts/build-inpage.mjs from src/browser/inpage-entry.ts. Do not edit.\n` +
    `export const INPAGE_JS: string = ${JSON.stringify(js)};\n`,
);
console.log(`inpage bundle: ${(js.length / 1024).toFixed(1)} KiB`);
